image: Visual Studio 2017
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\scripts\\ci\\windows\\run_with_env.cmd"
    TWINE_USERNAME: __token__
    TWINE_PASSWORD:
      secure: H7PI8imJTED02mGoIPpDn08+ku988jV+XX2oa4LAMHEHpa8DSnqMitpxieedr4YsP/xtLGqpk0rTFpVawtp3co6317tL8U0kNasd/ZppV7jDOiZN6qOaE97zKf7xOA37WsDd/5qhx1SRRRtLr5hepDu2dSKcQjH6w/rRtLP1SNNijnxEJNf1LZEirg5f55HvEplGwcTnM0V/F2FhgCpRuNFN9e3zcHXVTE9fS2m5BcU=

  matrix:
    - PYTHON: "C:\\Python36\\python"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37\\python"
      PYTHON_VERSION: "3.7.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64\\python"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64\\python"
      PYTHON_VERSION: "3.7.4"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # install.ps1 only needed for SDL1 stuff.
  # - "powershell buildconfig\\ci\\appveyor\\install.ps1"
  - "%PYPY_DOWNLOAD%"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\\%PYPY_VERSION%"
  - "%PYTHON% -m ensurepip"
  - "%PYTHON% -m pip install -U pip setuptools twine scikit-build wheel cmake"
  # - "%WITH_COMPILER% %PYTHON% -m buildconfig %USE_SDL2%"
  - "%PYTHON% setup.py bdist_wheel"
  # - "%WITH_COMPILER% %PYTHON% setup.py -setuptools %DISTRIBUTIONS%"
  - ps: "ls dist"

  # Install the wheel to test it
  - "%PYTHON% -m pip install --ignore-installed --pre --no-index --find-links dist/ pygeodiff"

# Appveyor's build step is specific to .NET projects, so we build in the
# install step instead.
build: off

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

test_script:
  - "%PYTHON% -c 'import pygeodiff as p; g=p.GeoDiff(); g.version();'"

# artifacts:
#  - path: 'dist\*.whl'
#    name: pypiartifacts

on_success:
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] %PYTHON% -m twine upload dist\\*.whl"